### ISSUE TITLE
Fetching order qty from clob_ord_t o

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#10]
Hi @hroptatyr 
Below is my Order placing code
 o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 2.0dd, 0.0dd, .lmt = 4500.00dd, .usr = (uintptr_t)"121"},NANPX);
      clob_oid_t  i;

if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   printf("orderid..%s\n", i.usr);

//Here I would like to get the pending qty from o.qty.dis but it displaying 0 thoug in orderbook its showing correct qty
  printf("Qty%lf",(o.qty.dis + o.qty.hid));  -----> Return 0  though 2 qty has been pushed

}   

Thanks

**Comment by hroptatyr** [comment]
What's `%lf`?

**Comment by shanhashcah** [comment]
%lf  for printing  double. Because we are passing double value.

**Comment by hroptatyr** [comment]
Ah okay, that doesn't work with my libc here, the l modifier is for integers only (to denote long int).

**Comment by shanhashcah** [comment]
Okay.. I am done it.
