### ISSUE TITLE
Create API for clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#11]
Hello @hroptatyr 

Thanks for your support!!

Sir I am having  all the code like order place, order cancel, order update in .c file and able to accept data from the user at runtime. By your immense help and support I have made this  code. If you need I can share the code with you. Now Sir I want to expose REST API for order place, order cancel, order update of  the .c file. In C language I think we can not build API. So Sir what is the correct way to build API in C.  Please help.

**Comment by shanhashcah** [comment]
Hi @hroptatyr 

Any suggestion Sir for my above issue.

**Comment by shanhashcah** [comment]
Hi @hroptatyr 

Any Update Sir about my last issue.

**Comment by hroptatyr** [comment]
Hi, I have no experience with REST APIs.  Neither as a user nor as a developer.

**Comment by shanhashcah** [comment]
Okay Sir thank you....

Any suggestion Sir how would I connect my c program I mean clob  with UI. I mean in real environment UI and app will be there. So if user wants to place an order he or she will use UI, in this case how clob communicate with UI or other application.

**Comment by hroptatyr** [comment]
If by UI you mean a console interface I could help you, there's even an example tool in the sources.  A FIX API is simple too.  But any other kind of interface I'm the wrong guy again.

**Comment by shanhashcah** [comment]
Sir FIX API mean? Is it available? Sir I am asking about GUI type UI which will connect my clob.  Sir which type of example tool available in the sources you mentioned.

**Comment by hroptatyr** [comment]
FIX is the standard protocol for financial exchanges. See https://www.fixtrading.org/.

The tool is `src/cloe.c`, it reads orders from a file and executes them in continuous auction mode.

I have no experience with GUIs.

**Comment by shanhashcah** [comment]
Okay...Sir thanks...
