### ISSUE TITLE
function and header file create for clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#12]
Hi @hroptatyr 

  I have created one header file called orderbook.h where I have defined one function called orderPlace and created one file called orderbook.c where I have implemented orderPlace function. Inside orderPlace function I have written order related code .But when I am going to compile orderbook.c file getting below error
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x20): undefined reference to `main'

Below is my orderbook.h and orderbook.c file.

orderbook.h
-------------------
#ifndef _ORDERBOOK_H
#define _ORDERBOOK_H

void orderPlace(char *out);

#endif

orderbook.c
--------------------
#include <stdio.h>
#include "clob.h"
#include "unxs.h"
#include "mmod-auction.h"
#include "nifty.h"
#include "dfp754_d64.h"
#include "orderbook.h"
#define NANPX (__builtin_nand64(""))

void orderPlace(char* out)
{

clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;

/* xetra example 1 */

       o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 2.0dd, 0.0dd, .lmt = 4500.00dd, .usr = (uintptr_t)"121"},NANPX);
      clob_oid_t  i;
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);
  sprintf(out,"orderid..%s\n",i.usr);

}

 unxs_clr(c.exe);
     
	clob_prnt(c);
        free_clob(c);         

}

**Comment by shanhashcah** [comment]
Sir any suggestion about my above issue.

**Comment by hroptatyr** [comment]
It's probably because you didn't write a `main()` routine.  You can always just create an object file instead of a binary by using the `-c` switch (which skips the linking step).

**Comment by shanhashcah** [comment]
Hi @hroptatyr 

I have done this way. But Sir in order book amount and price are not showing instead its generating below output.

LMT/BID
 +
 + 2
 +
 + 1
LMT/ASK
MKT/BID
MKT/ASK

**Comment by shanhashcah** [comment]
Any suggestion Sir..

**Comment by hroptatyr** [comment]
I think the markdown formatting garbled the output.  But othe than that, that used to work, you told me.  What's changed since?

**Comment by shanhashcah** [comment]
Actually Sir I am trying to call clob from go language. Regarding that I am creating one header file, c file and go file. Then I compiled c file, when I am trying to run go file not getting data in orderbook but orders are exists . Here are the codes.

orderbook.h
--------------
#ifndef _ORDERBOOK_H
#define _ORDERBOOK_H

char* show(char *out);

#endif

orderbook.c
--------------
#include <stdio.h>
#include "clob.h"
#include "unxs.h"
#include "nifty.h"
#include "dfp754_d64.h"
#include "orderbook.h"
#define NANPX (__builtin_nand64(""))


char* show(char *out)
{
char *orderid;
	clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;
       clob_oid_t  i;


/* xetra example 1 */

       o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 2.0dd, 0.0dd, .lmt = 4500.00dd, .usr = (uintptr_t)"121"},NANPX);
      
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);
 printf("Qty.."%f",(double)o.qty.dis);
 orderid=sprintf(out,"orderid..%s", i.usr);
}   
        
o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 3.0dd, 0.0dd, .lmt = 4501.00dd, .usr = (uintptr_t)"122"},NANPX);
      
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);
 orderid=sprintf(out,"orderid..%s", i.usr);
}

clob_prnt(c);

        free_clob(c);
	       


return orderid;

}

Then I compile orderbook.c and its compiled.

main.go
--------
package main

// #cgo CFLAGS: -g -Wall
// #include <stdlib.h>
// #include "orderbook.h"
import "C"
import (
	
	"unsafe"
)

func main() {

	ptr := C.malloc(C.sizeof_char * 1024)
	defer C.free(unsafe.Pointer(ptr))

	 C.show((*C.char)(ptr))

	
}
Here is the output
orderid..121
orderid..122
LMT/BID
 +
 + 2
 +
 + 1
LMT/ASK
MKT/BID
MKT/ASK

Most interestingly orders are placed successfully because thru printf  I getting the offerid but in orderbook instaed of price and amount its showing + symbols.

Please sir give me some hint or suggestion.

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir,, any suggestion/hint about my above issue.

**Comment by hroptatyr** [comment]
I have no idea, I've never used go.  Does it work when you call `show()` from the C language?  I.e. a main routine in C that calls `show()`.

**Comment by shanhashcah** [comment]
Ok Sir

Many thanks for your support.
