### ISSUE TITLE
free clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#13]
Hi @hroptatyr 

I have written one C code for order accept, order update and order cancel , if it is on real environment all time order engine should up and active. In this case how can I free clob by free_clob(c); code. Is free_clob(c); is required?  and if then how it will be implemented in production.

**Comment by hroptatyr** [comment]
`free_clob()` is the counterpart to `make_clob()`, i.e. when you need an order book you call `make_clob()`, when you no longer need the book call `free_clob()`

**Comment by shanhashcah** [comment]
Ok Sir Thanks..
Sir, in production there will be  millions of orders , so in this case will memory leak issue  occur? One more thing  Sir how many transactions can handle by clob? In production there will be huge traffic so can concurrency be handle by clob?

**Comment by hroptatyr** [comment]
Millions of unmatched orders is not a problem, a few megabytes.  Billions of unmatched orders could be problematic.  On a 384 GB machine you should be able to handle about 2 billion unmatched orders.

Concurrent workloads on a single book are not supported.  Throughput is okay-ish, about 4 to 10 million orders per second.  The latency is really bad: 100 ns per order typically but this can go up sporadically to 500 ns.

Also, when orders cannot be matched, i.e. only unmatchable orders are inserted, the throughput goes down to just under a million orders and the latency is always in the 500 ns ballpark.

**Comment by shanhashcah** [comment]
okay Sir  got it and thanks.

Sir I have one doubt  as below because you said "Concurrent workloads on a single book are not supported " in our last post.

suppose in BTC/USD symbol there could be huge transactions I mean pending order and unmatched order at a same time. In this case can clob be able to maintain concurrency i.e synchronization or something like this. If it is then every trader will get respective result. In production there are huge traffic so there will be huge concurrency.

Please sir guide me and if I understood wrong please correct me.

Many Thanks

**Comment by hroptatyr** [comment]
I don't understand what you mean by "maintain concurrency".  clob is not capable of multi-threading, i.e. accessing the book by two threads simultaneously.

What is huge traffic and huge concurrency in your eyes?

The 10 Morders/sec translate to 1.2 GB/s.  If they're all unmatched you can still write with about 100 MB/sec into the book.  But as I said before if there's say 3 billion orders on 1 side and 1 order that crosses them all is inserted, uncrossing could take up to 10 minutes (which translates to roughly 800 MB/s of uncrossing notifications).

**Comment by shanhashcah** [comment]
Ok Sir.

Whatever I understood that clob does not allow two traders simultaneously access the same pair. So in production if two/more traders wants to trade/place orders in the same book let's say BTC/USD pair at a same time then clob put them in a synchronization mode?  I am giving a very simple example because I want to clear my doubt.
In BTC/USD orderbook in ASK side only one order i.e  1 qty, 5000 price. Now trader A and trader B both wants to trade and suppose if they place  1 qty and 5000 price BID offer at a same time. Now whoever request come first he will get trade and other one request's will put as pending order. Here book needs to maintain synchronization. 

So sir please guide me.


A big thank you.

**Comment by hroptatyr** [comment]
Yes, it does that.

**Comment by shanhashcah** [comment]
Okay Sir many many thanks.

Let me test and will get any issue I'll post that.
