### ISSUE TITLE
Bulk Offer Placing Issue In Clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#16]
Hello Sir,

Here I am trying to push 100 orders at a time through loop price starting from 6001 to 6100 with 1 qty. In order book 6095 price not being pushed. But if I reduce the loop 100 times to 90 times then all 90 offers would have pushed. Similarly if I increment the loop time 100 to 200 and so on then in orderbook not all offers will not be pushed. I am sharing my simple code for placing 100 offers through loop which you can run from your end and please take a look of  order book that 6095 price is missing. But in order book must have 100 offers.

#include <stdio.h>
#include "clob.h"
#include "unxs.h"
#include "nifty.h"
#include "dfp754_d64.h"

#define NANPX (__builtin_nand64(""))

static void
send_trade(unxs_exe_t x)
{
   printf("Maker Matched Qty..%f\n",(double)x.qty);
   printf("Maker Matched Price...%f\n",(double)x.prc);
     
}

void orderPlace(clob_t c,double amount,double price, char orderid[19])
{

/* xetra example 1 */

      clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, amount,.lmt = price, .usr = (uintptr_t) orderid },NANPX);
      clob_oid_t  i;
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);

}   
        
/* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("2nd Order");
     printf("OrderId taker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);

   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
    send_trade(c.exe->x[i]);
   
   
}

unxs_clr(c.exe);

}

int
main(void)
{
	clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
       
       char x[19];
      
        double amount=1.0;
     
  for(int i=1;i<= 100  ;i++)
 {
    sprintf(x, "%d",i);
    char *out=strdup(x);
    double price=6000.0;
     double price1=price+i;
     printf("Price..%f\n",price1);
    orderPlace(c,amount,price1, out);

  }

       clob_prnt(c);
       free_clob(c);
	return 0;         

}

Please Sir help me out. I have been trying and testing it since yesterday.

A big thank you.

**Comment by shanhashcah** [comment]
Hello @hroptatyr  

Sir please help me about my issue.


Thank You

**Comment by shanhashcah** [comment]
Sir @hroptatyr 

Any suggestion, please help about my issue.

**Comment by hroptatyr** [comment]
That's reproducible.  There is an issue with the ASK side book.  I'm currently investigating.

**Comment by shanhashcah** [comment]
Okay Sir.. Thank you for looking the issue.

**Comment by shanhashcah** [comment]
Okay Sir. Let me check and I'll reply you back. Need some time.

**Comment by shanhashcah** [comment]
Ok. Now I am closing this issue and will reopen it if I will get any issue on this in future.

Many many thanks for your immense support.
