### ISSUE TITLE
OrderType  IOC and FOK in CLOB

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#17]
Hi @hroptatyr 

Sir, I have worked with clob so far like order placing that is GTC (Good Till Cancel) order type. So are IOC (Immediate Or Cancel) and FOK (Fill Or Cancel) option available in clob like other exchange?

Thank You

**Comment by hroptatyr** [comment]
Hi,
yes, ioc-executability can be tested with the `mmod_ioc()` routine, fok-executability with `mmod_fok()`.  The signature is in `mmod_ioc.h` and `mmod_fok.h` in src/.

**Comment by shanhashcah** [comment]
Ok. 
Sir I have full functionality for order place, trade, cancel, modify code and below is the code for order place and trade. Now Sir, in my existing code I want to add IOC and FOK features. 

#include <stdio.h>
#include "clob.h"
#include "unxs.h"
#include "mmod-auction.h"
#include "nifty.h"
#include "dfp754_d64.h"

         clob_t c;
	c = make_clob();
         c.exe = make_unxs(MODE_BI);

clob_ord_t  o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, amount, 0.0dd, .lmt = price, .usr = (uintptr_t) orderid},NANPX);

      clob_oid_t  i;

if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);

}   
        

         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
   //  printf("2nd Order");

     printf("OrderId taker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);

   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
    send_trade(c.exe->x[i]);
   
   
}

**Comment by hroptatyr** [comment]
yes, so check if the order is immediate first, and if so you place it, or cancel it otherwise.  Similarly for FOK.

**Comment by shanhashcah** [comment]
Sir if I want use  mmod_ioc() and mmod_fok() routine in my existing code then what shall I do?  Actually Sir I need these two features with my existing feature.

Many Thanks

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir

      Any suggestion about my issue. Please help.

Many Thanks

**Comment by hroptatyr** [comment]
I don't know your existing code but it's pretty simple:

    if (mmod_ioc(c, o)) {
        /* would be immediate */
        place_order(c, o);
    } else {
        /* would be cancelled */
        ...
     }

c being the clob_t object, o the order.  And for FOK:

    if (mmod_fok(c, o)) {
        /* would be filled */
        place_order(c, o);
     } else {
         /* would be killed */
         ...
     }

The ... needs to contain the code for sending an order rejection.

**Comment by shanhashcah** [comment]
Ok.  I want to add the code what you have shared in my code which is as below

clob_t c;
c = make_clob();
c.exe = make_unxs(MODE_BI);

clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, amount, 0.0dd, .lmt = price, .usr = (uintptr_t) orderid},NANPX);

  clob_oid_t  i;
if (o.qty.dis + o.qty.hid > 0.dd) {
/* put remainder of order into book */
i = clob_add(c, o);

printf("orderid..%s\n", i.usr);

}

//Print Trade details
for (size_t i = 0U; i < c.exe->n; i++) {

}

Thanks.

**Comment by shanhashcah** [comment]
Sir @hroptatyr 

Any comment sir about my above issue.

**Comment by hroptatyr** [comment]
Yes, if that is your `place_order()` routine then add:

    if (mmod_ioc(c, o)) {
        /* would be immediate */
        place_order(c, o);
    } else {
        /* would be cancelled */
        ...
    }

around it.  And you need to fill in the rejection bit.

**Comment by shanhashcah** [comment]
Ok. So if I try to integrate then my code would be

clob_t c;
c = make_clob();
c.exe = make_unxs(MODE_BI);

clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, amount, 0.0dd, .lmt = price, .usr = (uintptr_t) orderid},NANPX);

clob_oid_t i;

if (mmod_ioc(c, o)) {
   i = clob_add(c, o);
} else {
    /* would be cancelled */
    ... code for cancel
}
But Sir if I put order place code inside if block then new offer will be created but in IOC no offer has to be created. So Sir please correct my code.

Many Thanks

**Comment by hroptatyr** [comment]
No it needs to go before unxs_order().  IOC is an order type that inspects the book before interfacing the book.  First you look if the order is immediate, if so do the uncrossing.

To demonstrate in your snippet:

    clob_t c;
    c = make_clob();
    c.exe = make_unxs(MODE_BI);

    clob_ord_t o = {CLOB_TYPE_LMT, CLOB_SIDE_BID, amount, 0.0dd, .lmt = price, .usr = (uintptr_t) orderid};

    if (mmod_ioc(c, o)) {
        o = unxs_order(c, o, NANPX);
        if (o.qty.dis + o.qty.hid > 0.dd) {
            /* rest of the order is cancelled, i.e. not put on the book */
            ...
        }
    } else {
        /* order is not immediate, reject the whole order */
        ...
    }

**Comment by shanhashcah** [comment]
Ok. let me do it and I'll post if any difficulty.

Many Thanks

**Comment by shanhashcah** [comment]
Yes. I have done one sample code  for  IOC  , but I seen that remaining order not pushed into the book automatically  , I do not need to cancel the order explicitly. Clob take care about the remaining order for cancelation.
clob_t c;
c = make_clob();
c.exe = make_unxs(MODE_BI);

//Here I have placed one BID order

clob_ord_t  o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 1.00d, 0.0dd, .lmt = 500.00dd, .usr = (uintptr_t) "1"},NANPX);
      clob_oid_t  i;
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);

} 
clob_prnt(c);

//Now I want to place one ASK order with IOC type

clob_ord_t o1 = {CLOB_TYPE_LMT, CLOB_SIDE_ASK, 4.0dd, 0.0dd, .lmt = 300, .usr = (uintptr_t) "2"};

if (mmod_ioc(c, o1)) {
    o1 = unxs_order(c, o1, NANPX);
    if (o1.qty.dis + o1.qty.hid > 0.dd) {
        
    }
} else {
   
}

clob_prnt(c);

Above code is correct?

**Comment by shanhashcah** [comment]
Hello @hroptatyr 

Please Sir make some comment about my issue.

Thanks

**Comment by hroptatyr** [comment]
Looks okay to me.

**Comment by shanhashcah** [comment]
Ok Sir. Just I have one clarification that is  mmod_ioc and mmod_fok routine will take care about the order deletion. Don't I have  to delete the order explicitly? Actually I tested that these routine does that.

Many Thanks

**Comment by hroptatyr** [comment]
I don't understand what you mean. mmod_ioc and mmod_fok do not change the book, so no, they don't take care of order deletion.  If you find (by means of mmod_ioc) that an order is not immediate and you decide to put it into the book anyway, then that's just as fine as the opposite, finding an order that is immediate but not putting it into the book.

**Comment by shanhashcah** [comment]
Ok. I will do the complete program and will log if I will get any issue.

Thank you...
