### ISSUE TITLE
Data type for Order Price and Quantity in Clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#18]
Hello @hroptatyr  Sir,

Here I want to place 1 quantity and 0.00002372 price for an order and I have hard coded the price as below.

clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;
        /* xetra example 1 */
          o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, 1.0dd, 0.0dd, .lmt =0.00002372, .usr = (uintptr_t)"1"},NANPX);

If I iterate the orderbook  by writing below code 

//Code for iterating the orderbook
int j=0;
clob_aggiter_t i1= clob_aggiter(c, CLOB_TYPE_LMT, CLOB_SIDE_ASK);
	for (; clob_aggiter_next(&i1); j++) {
		 printf("Price:%f Amount:%f\n", (double)i1.p, (double)(i1.q.dis + i1.q.hid));
                 
	}

Getting Below output (Rounded value)
Output
-------------
Price:0.000024 Amount:1.000000

In  production  we should display the price  exactly whatever user has placed.

**Comment by hroptatyr** [comment]
Hi,
it's probably the cast from/to double that truncates the price.

    o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, 1.0dd, 0.0dd, .lmt =0.00002372dd, .usr = (uintptr_t)"1"},NANPX);

and then

    clob_prnt(c);

shows that the limit price is recorded properly.

**Comment by shanhashcah** [comment]
Ok. Actually Sir I need that price in a variable.

Please help.

**Comment by hroptatyr** [comment]
Then there's no problem, the price in `i1.p` is correct.

**Comment by shanhashcah** [comment]
clob_prnt(c)  just print the orderbook. But in production I want to organize the book, so I need that amount and price. That is why I want to keep that price and amount in a variable. If book stored that price exactly without rounding then that data type may I use to keep the value from i1.p and Sir what is that data type.

Please Sir guide me .

A big thanks for your support.

**Comment by hroptatyr** [comment]
What do you mean "in a variable".  `i1` *is* a variable.  And it holds the price and quantity.  Anyway, the type of `i1.p` is `_Decimal64` (aliased to `px_t`) and the type of `i1.q.dis` and `i1.q.hid` is `_Decimal64` (aliased to `qx_t`).

The type of `i1` is `clob_aggiter_t`, defined in clob.h and it contains a bit more than just the price and quantity it's totally safe for you to use that.

**Comment by shanhashcah** [comment]
Thank you @hroptatyr  Sir

I know i1 is a variable. I want to keep the value of i1.p into a variable. As you said the data type is _Decimal64. So is there any way to store the value of i1.p in a _Decimal64 type.

Please help.

**Comment by hroptatyr** [comment]
Yes, e.g.

    _Decimal64 x = i1.p;

**Comment by shanhashcah** [comment]
Ok. Now Sir I want to print x  then which format specifier I need to use inside  prinif() function .


Thank you

**Comment by hroptatyr** [comment]
Didn't we establish that your libdfp doesn't provide `printf` hooks?  With the hooks properly set up it's `%Df` for _Decimal64.

Other than that clob internally uses `d64tostr()` so you convert to string first then output the string.  The signature is

    d64tostr(char *restrict buf, size_t bsz, _Decimal64);

**Comment by shanhashcah** [comment]
Hi @hroptatyr  Sir
 %Df format specifier does not work , I tried as below

_Decimal64 x=i1.p;
printf("Price%Df",x);

Bur it  shows only Price%Df not the value of x.

And sir the return type of d64tostr(char *restrict buf, size_t bsz, _Decimal64); is int then how would I display the string? Can u please explain?

**Comment by hroptatyr** [comment]
char buffer[40];
    d64tostr(buffer, 40, 2383.0444dd);
    printf("Number: %s\n", buffer);

**Comment by shanhashcah** [comment]
Ok Sir A big thank you.

Now Sir I want to  use _Decimal64 strtod64(const char*, char**); function to convert string to _Decimal64.  For example

char *x="0.000023657";
I want to covert x into a _Decimal64. I can call  strtod64(const char*, char**) function. I think for  first  parameter can be x then what can be 2nd parameter?



Please Sir help me.

**Comment by hroptatyr** [comment]
Could be NULL, or a pointer to a `char*` where the point is stored where the parsing ended.  See `man strtod'.

**Comment by shanhashcah** [comment]
I was updating the comment while I got your comment. 

char x="0.000023657";

Actually Sir I  can pass x for the first parameter  then shall I pass NULL for 2nd parameter.

Thanks

**Comment by hroptatyr** [comment]
Yes.

**Comment by shanhashcah** [comment]
Ok Sir. Let me check both functions thoroughly and then I'll close the issue.

A huge thank you Sir for your support and co-operation.

**Comment by shanhashcah** [comment]
Hello Sir,

  What is the range of _Decimal64 data type in clob. 

Thank You

**Comment by hroptatyr** [comment]
16 digits, pretty much like double.

**Comment by shanhashcah** [comment]
Thanks @hroptatyr  Sir

So Sir price and quantity value must be within 16 digit. If it is more than 16 digit then remaining value will get discarded.

**Comment by hroptatyr** [comment]
Correct.

**Comment by shanhashcah** [comment]
Ok. Thank you for your support.

I am closing the issue as of now if I will get any on this I will reopen it.

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir,

 _Decimal64 date type if I use that source file  can  able to  compile with  gcc -c  ./test.c ./libclob.a  . I mean with -c option insted of -o 

Please help Sir...

**Comment by hroptatyr** [comment]
What's the error message?

**Comment by shanhashcah** [comment]
Actually Sir it is not showing any error message. It does not show any output. Let me explain.

First I am accepting value from go language and pass that value to C's function as below , that value are in string, in C that is char[19]. Now I am trying to convert that char array to decimal64 using _Decimal64 strtod64(const char*, char**) function as below
char number[19];
_Decimal x=strtod64(number,NULL); //converting string to decimal64

Now for showing that value in string 

char buf[256U];
d64tostr(buf, sizeof(buf),x);
printf("%s",buf); //it showing nothing

Will this function only works if we compile with gcc -o option? Or can I use  gcc -c option to compile because I can able to connect with  C through Go by gcc -c option only.


Thank you ..

**Comment by hroptatyr** [comment]
well yes it should work.  And also gcc -c just compiles a C file. You can't mention "libclob.a" there because that's already compiled.

    $ gcc -c ./test.c

should generate `test.o`.

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir,

    If I do not mention ./libclob.a then how clob will work?  Because in that file I have order place, order update  functionality using unxs_order function and all.

Thanks

**Comment by hroptatyr** [comment]
I don't know, but libclob.a is just an ar archive with a lot of .o files, see

    $ ar t libclob.a

you could add the test.o file to that archive (using `ar r`). I don't know what go supports when it comes to foreign function interfacing.  All I can say is that you cannot "link" a .o and a .a file into a .o file.

**Comment by shanhashcah** [comment]
Ok.. Thank you. Let try. If I'll face any issue I'll reopen it.

Thanks
