### ISSUE TITLE
calculation issue in clob orderbook (price/qty)--Not for all values 

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#19]
Hello Sir,

I have placed 0.0000232 price and 0.00000008 amount for ASK side and it is stored in orderbook. No  issues in this case. Here is the output

LMT/BID
LMT/ASK
0.00002320000000000000 0.00000008000000000000000+0.0
                       
Now I want to  match this order by placing 0.0000232 price and 0.00000006 amount for BID side.  So after matching with ASK side 0.00000002 amount must be remaining for ASK side.  But instead it is showing  as below 

LMT/BID
LMT/ASK
0.00002320000000000000 0.00000002000000000000001+0.0  // Here 1 has been added  an extra value at the end.

So Sir please look into this.

Many Thanks

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir

Any suggestion Sir about the issue.

Thanks

**Comment by hroptatyr** [comment]
Yes, you're obviously using doubles somewhere not _Decimal64 all the way through.  You're 0.00000002 is really a 0.00000001999999.

**Comment by shanhashcah** [comment]
Ok , Sir. If I want to pass double instead of _Decimal64  then what I will do? And Sir which one shall I use double or _Decimal64 in production level?

Please Sir guide me. 

Thank you.

**Comment by hroptatyr** [comment]
You can build libclob `--without-decimal`, that is run configure like so:

    $ ./configure --without-decimal

and all quantities and prices will be of type double.

The trade offs are: _Decimal64 is accurate but requires more care and is slower.
For double the opposites hold true: inaccurate, fast, supported in virtually all languages.

**Comment by shanhashcah** [comment]
Ok. @hroptatyr  Sir.

Actually I shall use _Decimal64 type whatever I understood from your help.

Actually Sir I want to use _Decimal64 data type in the following way

we have header file dfp754_d64.h ad its source file dfp754_d64.c  

Now I included dfp754_d64.h file in my test.c program.

test.h     -----> This my header file
--------
#ifndef _TEST_H
#define _TEST_H

char* show(char x[10]);

#endif


test.c
--------
#include "test.h"  ---->test.h header file included to use show() function
#include <stdio.h>
#include<stdlib.h>
#include "dfp754_d64.h"  

char* show(char p[10]) {
_Decimal64 q=strtod64(p,NULL);
char buf1[256U];
d64tostr(buf1,sizeof(buf1),q);
 printf("New..%s",p);
return p;
}

Now Sir I compiled this file as below

gcc -c test.c  

After compilation test.o file has been created

After that I included that test.h file in my go project to connect with C as below

package main

// #cgo CFLAGS: -g -Wall
// #include <stdlib.h>
// #include "test.h"    ----> Here test.h file has included
import "C"

import (
	"fmt"
	
)

func main() {
        
         y:="0.0008";
	 x := C.show(C.CString(y));  ----> calling show() function from C 
         fmt.Printf("%s..",x);
}

Here I have passed 0.0008 as string to C from go. Inside my test.c file strtod64 function is there , hopefully strtod64 will convert that string to _Decimal64 and using d64ostr function we can convert from _Decimal64 to string.

But Sir strtod64 function does not work in this situation. In go x is showing null.  W


Sir I have been trying this since tomorrow and more. But I won't be able to figure out yet.  Any thing am I missing?

Please help me Sir.

**Comment by hroptatyr** [comment]
Yes:

    char* show(char p[10]) {
      ...
      return p;
    }

Just returns the input argument. I don't know how go handles pointers but x and y should point to the same string.

Btw printing to buf1, as in

    d64tostr(buf1,sizeof(buf1),q);

is probably optimised out because you never do anything with buf1.

**Comment by shanhashcah** [comment]
ok. I changed the code but getting null

char* show(char p[10]) {

_Decimal64 q=str_to_d64(p,NULL);
char buf1[256U];
d64tostr(buf1,sizeof(buf1),q);
 printf("New..%s",buf1);
return buf1;
}

Sir one more thing I would like to share that what I have  explored that if test.c is the single. if I compile that c file by below command

gcc -o test test.c

and run ./test

then d64tostr and strtod64 works.

So Sir is there any differences?

**Comment by hroptatyr** [comment]
You cannot return a stack buffer.  Try:

    char *buf1 = malloc(256U);
    d64tostr(buf1, 256U, q);
    return buf1;

But you will need to keep track of the allocated memory and `free()` it at some point to avoid a memory leak.

**Comment by shanhashcah** [comment]
No Sir.. this mechanism also not working.

Sir if I configure clob by ./configure --without-decimal then will  my problem what I posted  be solved? Issue link given below.


https://github.com/hroptatyr/clob/issues/19#issue-991085588


Any other issue especially precision may I face after configuring clob by --without-decimal.


A big thank you for your continuous support and guidance.

**Comment by hroptatyr** [comment]
No, it will not be.  You cannot do decimal arithmetic on doubles precisely.

**Comment by shanhashcah** [comment]
Ok. Sir. Got it.

if I have test.c source file and this file contains d64tostr and strtod64 functions.

Now if I compile gcc -o test test.c libclob.a  and run ./test  then d64tostr and strtod64 function are working as expected.

But if I compile same test.c file like gcc -c test.c libclob.a then these function are not working.

I have been researching this but won't able to figure out.


Can you please check Sir?

**Comment by hroptatyr** [comment]
gcc -c libclob.a doesn't make sense because they are .o files already, inside an ar archive. See for yourself:

    $ ar t libclob.a

The functions (d64tostr and strtod64) are in `libclob_a-dfp754_d64.o` inside libclob.a

You might extract them if you wish:

    $ ar x libclob.a libclob_a-dfp754_d64.o

**Comment by shanhashcah** [comment]
Yes. linclob.a contain the dfp754_d64.o, I know that.

Actually I want to use functions (d64tostr and strtod64) in my test.c file that is why I am linking libclob.a otherwise it will throw unreferenced error for d64tostr , strtod64 functions.

Sir this is not the case.

My problem is these functions are not working with gcc -c test.c  but it is working with gcc-o test.c

Thanks Sir

**Comment by hroptatyr** [comment]
Yes I know.  gcc -c only compiles test.c to test.o. Skipping the linker step altogether.  However, you need to do the linking if you want to use these functions.

**Comment by shanhashcah** [comment]
So Sir how will I link libclob.a in this case I mean gcc -c test.c

**Comment by hroptatyr** [comment]
When you've done gcc -c test.c, you can use

    $ gcc -o test test.o libclob.a

to do the linking.

**Comment by shanhashcah** [comment]
Sir I can not create an object file as test.o does not have main. That is why I am getting below error

.text+0x20): undefined reference to `main'

Sir one thing I would like to share with you that in test.c file  also has  unxs_order() order function. And I am able to placing order and match also. unxs_order function is working well though I compiled with gcc -c  test.c  libclob.a . So why can't d64tostr and strtod64 is not working in that test.c file.  Here is the catch.

Thanks

**Comment by hroptatyr** [comment]
I don't quite understand what you need.  If you want to link the program, you write a `main.c` with a main() routine and use gcc -c main.c, then you link all the stuff:

    $ gcc -o test main.o test.o libclob.a

**Comment by shanhashcah** [comment]
I have test.c file in this file unxs_order function along with d64tostr and strtod64 functions are exist.  Now I want to connect with go language because of API creation. To connect with go I have to compile that test.c file like gcc -c test.c libclob.a command. After that test.o file will be created.  Everything is working fine except d64tostr and strtod64 functions. 

Suppose if I do not need go language connection then  I shall compile gcc -o test test.c command. Here d64tostr, strtod64 working well. 

Actually I need d64tostr, strtod64 function should be work if I compile my source file like gcc -c test.c libclob.

**_If we think gcc -c test.c libclob.a here -c skipping the linking option then why unxs_order function works not d64tostr function.  This my confusion Sir_**

Correct me Sir if I have some misconception.

Many Thank you Sir

**Comment by hroptatyr** [comment]
>  I have to compile that test.c file like gcc -c test.c libclob.a

That statement makes no sense. This is just the same as `gcc -c test.c` without the libclob.a.

>  Everything is working fine except d64tostr and strtod64 functions.

Yes because they aren't in the test.o, they are in libclob.a, and need to be linked.

If you don't want standalone executables and go accepts shared objects, you could do:

    $ gcc -shared -o test test.c libclob.a

but for that to work you probably need to recompile libclob.a with -fPIC again.

> then why unxs_order function works not d64tostr function

I doubt that.  It's unclear to me what you mean by "works", compiles, runs?

Check the output of:

    $ nm test.o

If the routine unxs_order() is in there with an address then I don't know.  On my system it's just as undefined as d64tostr and strtod64.

**Comment by shanhashcah** [comment]
Thanks for your support.

Sir whatever I have understood  from your answer that if I want to connect my test.c which contains d64str, strtod64, unxs_order functions with go language then  I need to follow below steps.

A.  I need to create a shared object like  gcc -shared -o test test.c libclob.a 

B. I need to recompile with -fPIC command.

Sir please give me the steps for -fPIC option. I mean how to recompile.

Anything am I missing Sir?

Thank You

**Comment by hroptatyr** [comment]
A. It's a stab in the dark, isn't there documentation for the go C API? gcc -shared is a way to create a dynamic library (.so), correctly you'd call

    $ gcc -shared -fPIC -o test.so test.c libclob.a

B. Run ./configure like

    $ ./configure CFLAGS=-fPIC

**Comment by shanhashcah** [comment]
Hello @hroptatyr  Sir

I hove done these two steps. But not got output as expected.
First of  all Sir .so file  not found in my directory where I ran gcc -shared -fPIC -o test.so test.c libclob.a command.

2nd Sir after retrieving value from go and passed to C for using strtos64, d64tostr functions I am getting below output and code also given below
char stramt[10] // Here I a have passed a string value from go to stramt variable
_Decimal64 q=strtod64(stramt,NULL);
char buf1[256U];
d64tostr(buf1,sizeof(buf1),q);
printf("StringToDecimal64.%s",buf1);

Output
---
StringToDecimal64.`g▒    ----------------->It is showing some garbage value

Thanks Sir

**Comment by hroptatyr** [comment]
I'm puzzled, did the first step succeed or not? If not, how could you do the second step?

I just tried with gcc here on my system.  Works as described.

**Comment by shanhashcah** [comment]
Sir after running first step I am getting below message 

/usr/bin/ld: libclob.a(libclob_a-clob.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status


Now shall I go for the second step or not? When test.so file will be created after first step or second step?

**Comment by hroptatyr** [comment]
Yes, the libclob.a needs to be built with -fPIC

    $ ./configure CFLAGS=-fPIC
    $ make clean all

**Comment by shanhashcah** [comment]
Sir I have done with these steps. But I am not getting .so file.  Can I test with go?

Thanks

**Comment by hroptatyr** [comment]
Then building with -fPIC didn't work.  All objects that go into libclob.a must be compiled with -fPIC, if not you will not be able to build a shared object (so).

**Comment by shanhashcah** [comment]
> Sir I have done with these steps. But I am not getting .so file. Can I test with go?
> 
> Thanks

I just checked whether it works or not, now I getting below output

StringToDecimal64.`

earlier it was  StringToDecimal64.`g▒

**Comment by shanhashcah** [comment]
> Then building with -fPIC didn't work. All objects that go into libclob.a must be compiled with -fPIC, if not you will not be able to build a shared object (so).

Now Sir what shall I do? Sir I wonder why strtod64 and d64tostr is not working here where other function like unxs_order is working? Both are in libclob.a file.

Thank You Sir

**Comment by hroptatyr** [comment]
I doubt that unxs_order is working. How do you conclude that? Are you getting the test.so now?

**Comment by shanhashcah** [comment]
Yes Sir unxs_order is working I tested. Because I directly passed a double value to the orderbook not _Decimal64 type. Here I used above two steps.  I successfully able to placed an order using unxs_order function. Instead of double if I try to pass _Decimal64 type using strtod64 and d64tostr that time I am getting a garbage value which I already showed you . As it is showing garbage value then no offer is placing.

**Comment by hroptatyr** [comment]
No idea, with your code as above it works for me.

**Comment by shanhashcah** [comment]
Sir @hroptatyr  have you tested with go? Are strtod64, d64tostr these functions working? What wrong am I doing?

Any help Sir...

Thanks

**Comment by hroptatyr** [comment]
No, I don't have go.  I tested using a simple C program which calls your show() in test.so.

**Comment by shanhashcah** [comment]
Sir @hroptatyr 

Here no error is giving but test.so file is created. Sir if test.so file is not created then how go can able to connect with C for using unxs_order function and placed an order? Here Sir d64tostr and strtod64 is not working? 

Anything Sir am I missing or have I some misconception in this?


Thank You Sir..

**Comment by hroptatyr** [comment]
Just to be clear

    $ gcc -shared -o test.so test.c libclob.a

gives no error and yet does not output a `test.so`?

I cannot explain why unxs_order() would work in your case, it doesn't work on my machine. The error on my machine is:

    Error: undefined reference to `unxs_order'

**Comment by shanhashcah** [comment]
If I get test.so then unxs_order,strtod64,d64tostr all these function will work?

But Sir I am not getting test.so file.


Any other way to make it works?

Actually Sir after taking  amount and price  from the trader through go language  then I will convert that amount and price in _Decimal64  data type and will push into clob engine. This Sir my main goal. I have trying this for few days but I won't.

**Sir  if I use Decimal64 data type without using strtod64  function will clob accept that? Because Sir I have one other C code for converting string to decimal64. Sir if I use  that code base to convert decimal64 data type then I pass it to clob, will it possible?**

Thank you Sir....

**Comment by hroptatyr** [comment]
Yes, it will work. It doesn't matter who or hat creates the _Decimal64.

**Comment by shanhashcah** [comment]
Thanks @hroptatyr 

Sir I have tried it, but clob asking about _Decimal64 and whatever code I have got, it is Decimal64.  Let me explain

Here I have Decimal64.h and Decimal64.c file. If I include Decimal64.h header file then I can use Decimal64 data type as below.

ex:- Decimal64 x;

But clob accept only _Decimal64 type.

If clob  accept decimal64 irrespective of Decimal64 or _Decimal64 then Sir hopefully would have solve this problem. But again I 
 got stuck.

**Comment by hroptatyr** [comment]
There's only one decimal64 type as defined by IEEE-754, well there's two but the other one is for the Power architecture only.  Clob will happily accept any 64bit number and interpret it as decimal-float.  You can write a little "converter" in your code like so:

    union decimals {
        _Decimal64 for_clob;
        Decimal64 for_other;
    };

And then when you read it off the other library you put it into the `for_other` slot and when you read or write to clob you put it into the `for_clob` slot:

    union decimals x;

    x.for_other = read_decimal(...);
    clob_add(..., .lmt = x.for_clob, ...);

**Comment by shanhashcah** [comment]
Sir @hroptatyr 

In other header file  _Decimal64  defined as  decimal64.  Below is my code and I am getting below error

union decimals {
    _Decimal64 for_clob;
    decimal64  for_other;
};
union decimals x;
x.for_clob=x.for_other;

 **error: incompatible types when assigning to type ‘_Decimal64’ from type ‘decimal64 {aka struct <anonymous>}’
 x.for_clob=x.for_other;**

Sir both are decimal64 but clob does not accept that. If you need I can share that decimal64 library code base which I found.

Many Thank You Sir

**Comment by hroptatyr** [comment]
No, you cannot assign them to each other, the way it works is you put one in one slot and read from the other.

    _Decimal64 x = 4.dd;
    decimal64 y;
    union decimals z;
    z.for_clob = x;  /* works */
    y = z.for_other;  /* works too */

**Comment by shanhashcah** [comment]
Sorry @hroptatyr  Sir today I am being late to  hit and try from my side of your suggestion. 

Sir ultimately I  need to pass _Decimal64 to unxs_order function. Let me explain I am accepting value from the user as string and convert into decimal64 using other library. Then this decimal64 I need to convert _Decimal64 for clob compatible.  From your suggestion  x is already in _Decimal64 and you are assigning _Decimal64  to z.for_clob and z.for_other to y. But this is not our case. Our case is decimal64 to _Decimal64.

Correct me Sir I am doing something wrong.

Thanks

**Comment by hroptatyr** [comment]
It works both ways:

    z.for_other = y;
    x = z.for_clob;

**Comment by shanhashcah** [comment]
Sir @hroptatyr  Thanks

union decimals {
_Decimal64 for_clob;
decimal64 for_other;
};

decimal64 y;

union decimals z;
z.for_other = y; // Here y is decimal64 , So I can assign to z.for_other as for-other also decimal64

But  x = z.for_clob; //Here it is giving an error 

Moreover how would I assign decimal64 i.e y to _Decimal65 i.e for_clob of union decimals

Here is my code snippet

union decimals {
    _Decimal64 for_clob;
    decimal64  for_other;
};

union decimals x;
char amount[100];
decContext set;
printf("Enter Amount\n");
  scanf("%s",&amount);
decimal64FromString(&x.for_other,amount, &set);
x=x.for_other;
o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);

or if I do below way
x.for_clob=x.for_other;
o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);
then I am getting below error
error: incompatible types when assigning to type ‘_Decimal64’ from type ‘decimal64 {aka struct <anonymous>}’
 x.for_clob=x.for_other;

**Comment by hroptatyr** [comment]
What's this?

     x=x.for_other;

I'd kill that line and use:

    o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x.for_clob, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);

**Comment by shanhashcah** [comment]
> ```
> 
> I'd kill that line and use:
> 
> ```
> o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x.for_clob, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);
> ```

decimal64 y;
Here If I want to use x.for_clob then I have to assign x.for_clob with that decimla64 type like x.for_clob=y but again I am getting type conversion decimal64 to _Decimal64 erro

**Comment by shanhashcah** [comment]
> > o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x.for_clob, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);
> 
> decimal64 y;
> Here If I want to use x.for_clob then I have to assign x.for_clob with that decimla64 type like x.for_clob=y but again I am getting type conversion decimal64 to _Decimal64 erro

**Comment by hroptatyr** [comment]
I don't understand.  You'd use

    x.for_other=y;

**Comment by shanhashcah** [comment]
I have tried it. Now we can assign decimal64 value to _Decimal64 using union.

But Sir if I enter 0.0003 as a quantity and this value fetched by other library and pass it to union. Then I pass to unxs_order  function like 
o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x.for_clob, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);
But getting output in orderbook
0.0000000000003 for quantity.

It probably other library issue, I am no sure. 

Thank You Sir for your support

**Comment by shanhashcah** [comment]
Okay Sir.. Let me try with another option. A big thank you for your continuous support and guidance. Sir if I need your help then I'll reopen it. Now I am closing the issue.

Many Thank You Sir....
