### ISSUE TITLE
Order accept dynamically

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#2]
Hi @hroptatyr 

Here I am trying to accept amount,price from the user  but in orderbook it is showing too many zeros after value. I am sharing my code and output as below.

int
main(void)
{
	clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;
       double amt;
       double price;
     printf("Enter Amount");
    scanf("%lf",&amt);
   printf("Enter Price");
  scanf("%lf",&price);

        
	/* xetra example 1 */

          o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, amt , 0.0dd, .lmt =price, .usr = (uintptr_t)"121"},NANPX);
          
if (o.qty.dis + o.qty.hid > 0.dd) {
        /* put remainder of order into book */
        clob_oid_t i1 = clob_add(c, o);
       //printf("orderid..%lu\n", i1.usr);
       printf("orderid..%s\n", i1.usr);

        }

         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("2nd Order");
     //printf("OrderId taker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    //printf("OrderId maker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
  printf("OrderId taker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);

   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
    send_trade(c.exe->x[i]);
   
   
}
 unxs_clr(c.exe);
       

	clob_prnt(c);
        free_clob(c);
        
          

                  
           
          
	return 0;
}

Output
Enter Amount
0.00001
Enter Price
0.000000789
orderid..121
LMT/BID
LMT/ASK
0.0000007890000000000000 0.00001000000000000000+0.0
                         0.00001000000000000000+0.0 1
MKT/BID
MKT/ASK

In orderbook amot and price are taking zeros aftre showing original values.

**Comment by hroptatyr** [comment]
That's because you're operating in `_Decimal64` mode but you feed it ordinary doubles.  Choose one.

I've updated the code so you can now configure clob **not** to use _Decimal64.

    ./configure --without-decimal

should do the trick.

**Comment by shanhashcah** [comment]
Thanks @hroptatyr 

If I want to keep _Decimal64 mode , if user pass ordinary double then it should reflect ordinary double in order book or if somebody passed _Decimal64 based doubled then it will display that. I mean I should have larger decimal.

again I am sharing my code

#include <stdio.h>
#include "clob.h"
#include "unxs.h"
#include "mmod-auction.h"
#include "nifty.h"
#include "dfp754_d64.h"

#define NANPX (__builtin_nand64(""))

static void
send_trade(unxs_exe_t x)
{
   printf("Qty..%f\n",(double)x.qty);
   printf("Price...%f\n",(double)x.prc);
     
}

int
main(void)
{
	clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;
       double amt;
       double price;
     printf("Enter Amount\n");
    scanf("%lf",&amt);
   printf("Enter Price\n");
  scanf("%lf",&price);

        
	/* xetra example 1 */

          o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, amt , 0.0dd, .lmt =price, .usr = (uintptr_t)"121"},NANPX);
          
if (o.qty.dis + o.qty.hid > 0.dd) {
        /* put remainder of order into book */
        clob_oid_t i1 = clob_add(c, o);
       //printf("orderid..%lu\n", i1.usr);
       printf("orderid..%s\n", i1.usr);

        }

         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("2nd Order");
     //printf("OrderId taker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    //printf("OrderId maker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
  printf("OrderId taker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%s\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);

   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
    send_trade(c.exe->x[i]);
   
   
}
 unxs_clr(c.exe);
       

	clob_prnt(c);
        free_clob(c);
        
          

                  
           
          
	return 0;
}

Thank You..

**Comment by hroptatyr** [comment]
> if user pass ordinary double then it should reflect ordinary double in order book

No, you have to choose, either _Decimal64 or double. They are incompatible and cannot be mixed in one order book.

**Comment by shanhashcah** [comment]
Okay.. got it.

Now I want that  user can place ASK/BID side dynamically. So for example I am assigning one char[] variable  and try to pass that variable unxs_order function agrument;

char side[]="CLOB_SIDE_ASK";

 o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, side, amt , 0.0dd, .lmt =price, .usr = (uintptr_t)"121"},NANPX);

But I am getting below error 

error: incompatible types when initializing type ‘enum <anonymous>’ using type ‘char *’
           o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, side, amt , 0.0dd, .lmt =price, .usr = (uintptr_t)"121"},NANPX);

Thanks...

**Comment by hroptatyr** [comment]
Well, you need to parse your user's input:

    char side[] = "CLOB_SIDE_ASK";
    clob_side_t parsed_side;
    if (!strcmp(side, "CLOB_SIDE_ASK")) {
        parsed_side = CLOB_SIDE_ASK;
    } else if (!strcmp(side, "CLOB_SIDE_BID")) {
        parsed_side = CLOB_SIDE_BID;
    }
    o = unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, amt, 0.dd, ...});

**Comment by shanhashcah** [comment]
Okay.. many Thanks I have implemented that.

As of now I am done order accept from user level and return matching order if applicable. For update and delete I need order id which suppose to be pass by the user at runtime  that is why I am keeping all orders in hash table and in this hash table,  orderid is the key.  When  orders are matched I am deleting those matched orders from hash table. In my last github issue discussion you suggested about has table. Now Sir I have a small doubt in production environment there are bulk orders that needs to be inserted in hash table  and deleted as per requirement. In that case hash table will be capable for storing such bulk orders. If you ask I can share my code to u also.

**Comment by shanhashcah** [comment]
Hi @hroptatyr 

Any suggestion Sir about my last post.

**Comment by hroptatyr** [comment]
Huh, did I miss a question?  I thought you told me that everything was working fine.

**Comment by shanhashcah** [comment]
Actually Sir the bottom line of my last question which I posted yesterday that I am using Hash table to keep all offers so that whenever user wants to update/delete an order I can take that respective  clob_oid_t from the Hash table of that offerid then I can delete/update. Now I am doubting that is Hastable is capable to perform such operation which I implemented in production where there are huge transactions. If you need I can sshare my entire code.

**Comment by hroptatyr** [comment]
Okay, well, using a hash table was just a suggestion.  Any kind of lookup data structure will do.  And by huge you mean more orders than there is RAM on your machine?

**Comment by shanhashcah** [comment]
Ok Thanks @hroptatyr 

So I am taking Hash table for keeping orders in production. 

Now  need to put backup all orders in database. So can please suggest which database shall I use.


Thank You

**Comment by hroptatyr** [comment]
Sorry, that's not for me to say.  Use whatever you use normally.

**Comment by shanhashcah** [comment]
Thanks..

Sir, I am taking hash table to put all orders as I already said in my last conversion. Sir I am sharing my below code and  the problem with my code is has table is not dynamic. So Sir please correct me how make my hash table dynamic. It should grows and shrink automatically.

#define SIZE 20


struct DataItem {
   clob_oid_t data;   
   int key;
};

struct DataItem* hashArray[SIZE]; 
struct DataItem* dummyItem;
struct DataItem* item;

int hashCode(int key) {
   return key % SIZE;
}

struct DataItem *search(int key) {
   //get the hash 
   int hashIndex = hashCode(key);  
	
   //move in array until an empty 
   while(hashArray[hashIndex] != NULL) {
	
      if(hashArray[hashIndex]->key == key)
         return hashArray[hashIndex]; 
			
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }        
	
   return NULL;        
}

void insert(int key,clob_oid_t data) {

   struct DataItem *item = (struct DataItem*) malloc(sizeof(struct DataItem));
   item->data = data;  
   item->key = key;

   //get the hash 
   int hashIndex = hashCode(key);

   //move in array until an empty or deleted cell
   while(hashArray[hashIndex] != NULL && hashArray[hashIndex]->key != -1) {
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }
	
   hashArray[hashIndex] = item;
}

struct DataItem* delete(struct DataItem* item) {
   int key = item->key;

   //get the hash 
   int hashIndex = hashCode(key);

   //move in array until an empty
   while(hashArray[hashIndex] != NULL) {
	
      if(hashArray[hashIndex]->key == key) {
         struct DataItem* temp = hashArray[hashIndex]; 
			
         //assign a dummy item at deleted position
         hashArray[hashIndex] = dummyItem; 
         return temp;
      }
		
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }      
	
   return NULL;        
}

void display() {
   int i = 0;
	
   for(i = 0; i<SIZE; i++) {
	
      if(hashArray[i] != NULL)
         printf(" (%d,%d)",hashArray[i]->key,hashArray[i]->data.usr);
      else
        printf(" ~~ ");
   }
	
   printf("\n");
}


Thanks in advance

**Comment by hroptatyr** [comment]
I can't help you with that one, sorry.

**Comment by shanhashcah** [comment]
Okay Sir... Thank you Let me try.. I am closing this issue.
