### ISSUE TITLE
How to check clob_t is initilize or not

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#20]
Hello Sir,

  To place an order I have below code
clob_t c;
c = make_clob();
 c.exe = make_unxs(MODE_BI);

o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, x.for_clob, 0.0dd, .lmt =m, .usr = (uintptr_t)"1"},NANPX);

Before put c into unxs_order function I need to check whether c has been initialized or not I mean below lines are called or not  before put into unxs_order function;
c=make_clob();
c.exe = make_unxs(MODE_BI); 

Actually Sir I have tried like c==NULL but it does not work.

Thanks

**Comment by hroptatyr** [comment]
You cannot.  It's your code, there's no way to write code that checks if you wrote a certain piece of code.  Are you thinking of generating code somehow?

**Comment by shanhashcah** [comment]
Sir @hroptatyr 
If I put c into unxs_order() function with out c = make_clob(); c.exe = make_unxs(MODE_BI); then I get Segmentation fault (core dumped) error. So I need to check whether c is properly initialized or not?

Thank You

**Comment by hroptatyr** [comment]
No you don't. You just initialize it properly.

**Comment by shanhashcah** [comment]
Okay Sir. If I'll get any difficulty then I'll reopen it.
