### ISSUE TITLE
Order Updating Issue at fulfil/partial time

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#3]
Hi @hroptatyr 

I have put all functionality in one code and user can do insert,update or delete order dynamically. Here every thing is dynamic.

Now Sir I am facing one major problem in order updation.  Let me explain suppose  trader A has placed 1 qty, 1000 price ASK order with order id 1. Now it is pending order. Then trader  B has placed 0.5 qty ,500 price BID order with orderid 2.  Here is the order book.

LMT/BID
500 0.5+0.0
    0.5+0.0 2
LMT/ASK
1000 1+0.0
     1+0.0 1
MKT/BID
MKT/ASK

Now trader A is going  to change his price 500 and his order gets filled by 0.5 qty and 0.5 qty is still remain in orderbook for orderid 1.  Please see the order book

LMT/BID
LMT/ASK
500 0.5+0.0
    0.5+0.0 3
MKT/BID
MKT/ASK

Then another trader lets say trader C has placed 0.1 qty with 25 price BID order for order id 3 and is is also pending. 
Please see the orderbook.

LMT/BID
25 0.1000000000000000+0.0
   0.1000000000000000+0.0 4
LMT/ASK
500 0.5+0.0
    0.5+0.0 3
MKT/BID
MKT/ASK

Again trader A is going to update his price 25 for order id 1.  So in order book orderid 1 should remain 25 price for 0.4 qty. But in my case order book keeps old order price 500 price, 0.5 qty still.  It must have only 25 price for 0.4 qty. Please see my orderbook.  

LMT/BID
LMT/ASK
25 0.4000000000000000+0.0
   0.4000000000000000+0.0 5
500 0.5+0.0
    0.5+0.0 3
MKT/BID
MKT/ASK

Sir I am sharing my order updation code with you. Please help me out. if you need I can share my entire code.

// Here I am declaring hash table for keeping orders 

#define SIZE 20

struct DataItem {
   clob_oid_t data;   
   int key;
};

struct DataItem* hashArray[SIZE]; 
struct DataItem* dummyItem;
struct DataItem* item;

int hashCode(int key) {
   return key % SIZE;
}

struct DataItem *search(int key) {
   //get the hash 
   int hashIndex = hashCode(key);  
	
   //move in array until an empty 
   while(hashArray[hashIndex] != NULL) {
	
      if(hashArray[hashIndex]->key == key)
         return hashArray[hashIndex]; 
			
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }        
	
   return NULL;        
}

void insert(int key,clob_oid_t data) {

   struct DataItem *item = (struct DataItem*) malloc(sizeof(struct DataItem));
   item->data = data;  
   item->key = key;

   //get the hash 
   int hashIndex = hashCode(key);

   //move in array until an empty or deleted cell
   while(hashArray[hashIndex] != NULL && hashArray[hashIndex]->key != -1) {
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }
	
   hashArray[hashIndex] = item;
}

struct DataItem* delete(struct DataItem* item) {
   int key = item->key;

   //get the hash 
   int hashIndex = hashCode(key);

   //move in array until an empty
   while(hashArray[hashIndex] != NULL) {
	
      if(hashArray[hashIndex]->key == key) {
         struct DataItem* temp = hashArray[hashIndex]; 
			
         //assign a dummy item at deleted position
         hashArray[hashIndex] = dummyItem; 
         return temp;
      }
		
      //go to next cell
      ++hashIndex;
		
      //wrap around the table
      hashIndex %= SIZE;
   }      
	
   return NULL;        
}

void display() {
   int i = 0;
	
   for(i = 0; i<SIZE; i++) {
	
      if(hashArray[i] != NULL)
         printf(" (%d,%d)",hashArray[i]->key,hashArray[i]->data.usr);
      else
        printf(" ~~ ");
   }
	
   printf("\n");
}

static void
send_trade(unxs_exe_t x)
{
   printf("Qty..%f\n",(double)x.qty);
   printf("Price...%f\n",(double)x.prc);
     
}

///Here I am taking  old order id, amout ,price , then search clob_oid_t from the hashtable based on the key and if this order gets match then emove the clob_oid_t from the hash table.

 printf("Enter OfferId\n");
    scanf("%d",&orderid);
   printf("Enter Amount\n");
   scanf("%lf",&amt);
    printf("Enter Price\n");
     scanf("%lf",&price);
  clob_oid_t i1;
    item = search(orderid);  //hash table lookin the existing order  id 
   if(item != NULL) {
      printf("Element found\n");
       i1=item->data;
     if (clob_del(c, i1) < 0) {
    puts("error, order doesn't exist");
     }

        
clob_ord_t o1 = unxs_order(c, (clob_ord_t){i1.typ, i1.sid, amt , 0.0dd,.lmt =price, .usr = i1.usr},NANPX);
if (o1.qty.dis + o1.qty.hid > 0.dd) {
    /* put remainder of order into book */
   clob_oid_t i2 = clob_add(c, o1);
   //printf("orderid..%lu\n", i2.usr);
   printf("Order Updated");
}   
        
double taker_remainqty;
double maker_remainqty;
int orderidtaker;
int count=0;
         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("2nd Order");
     printf("OrderId taker..%d\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%d\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);
  orderidtaker=c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr;
   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
  taker_remainqty=(double)t1.dis;
  maker_remainqty=(double)m1.dis;
if(maker_remainqty==0)
{
   item = search(c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
   delete(item); // this for hastable
}
count++;
    send_trade(c.exe->x[i]);
}
if(count!=0)
{
if(taker_remainqty==0)
{
   item = search(orderidtaker); // this for hastable
   delete(item); // this for hastable
}

}

  clob_prnt(c);
   unxs_clr(c.exe);

   } else {
      printf("Element not found\n");
   }

**Comment by hroptatyr** [comment]
Looks like you added the new order but forgot to delete the old one.

**Comment by shanhashcah** [comment]
No Sir, if we see the scenario first time 
when trader A updated his price 1000 to 500  for order id 1 which I have describe in detail in my last post  and in BID there was 0.5 qty and 500 price order, so that ASK order get matched by 0.5 qty and in order book 1000 price was not there 

LMT/BID
LMT/ASK
500 0.5+0.0
0.5+0.0 3
MKT/BID
MKT/ASK

So obviously I had deleted old order I mean 100 price.

Then another trader lets say another trader has placed 0.1 qty with 25 price BID order for order id 3 and is is also pending.
Please see the orderbook.

LMT/BID
25 0.1000000000000000+0.0
0.1000000000000000+0.0 4
LMT/ASK
500 0.5+0.0
0.5+0.0 3
MKT/BID
MKT/ASK

Again trader A is going to update his price 25 for order id 1. So in order book orderid 1 should remain 25 price for 0.4 qty. But in my case order book keeps old order price 500 price, 0.5 qty still. It must have only 25 price for 0.4 qty. Please see my orderbook.

LMT/BID
LMT/ASK
25 0.4000000000000000+0.0
0.4000000000000000+0.0 5
500 0.5+0.0
0.5+0.0 3
MKT/BID
MKT/ASK

So here 500 price not been deleted.

Here  I am getting inside if message.

 if (clob_del(c, i1) < 0) {   
    puts("error, order doesn't exist");
     }


See my deleted and updated code only.

 clob_oid_t i1;
    item = search(orderid); //Here I am searching clob_od_t from hash table based on orderid
   if(item != NULL) {
      printf("Element found\n");
       i1=item->data;  //Here I am assigning clob_Oid_t from hashtable to i1
     if (clob_del(c, i1) < 0) {   //Deleting the oldorder
    puts("error, order doesn't exist");
     }

        
clob_ord_t o1 = unxs_order(c, (clob_ord_t){i1.typ, i1.sid, amt , 0.0dd,.lmt =price, .usr = i1.usr},NANPX);  //Updating the old order
if (o1.qty.dis + o1.qty.hid > 0.dd) {
    /* put remainder of order into book */
   clob_oid_t i2 = clob_add(c, o1);
   //printf("orderid..%lu\n", i2.usr);
   printf("Order Updated");
}

**Comment by hroptatyr** [comment]
If `clob_del()` returns with an error then `i1` is not correct, and therefore the order isn't deleted from the book.

**Comment by shanhashcah** [comment]
Ok Sir.. Thanks
It was my fault...
