### ISSUE TITLE
Order storing issue 

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#4]
Hello Sir

 I am keeping the order clob_oid_t in hashmap as key and value pair. And below is my code snippet  .

void orderplace(clob_t c,double amt,double price,char output[19],struct hashMap *hashTable)
{
clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, amt, 0.0dd, .lmt =price, .usr = (uintptr_t) output},NANPX);
          

       if (o.qty.dis + o.qty.hid > 0.dd) {
        /* put remainder of order into book */
        clob_oid_t i = clob_add(c, o);
       //printf("orderid..%lu\n", i.usr);
         printf("orderid..%s\n", i.usr);
         insertMap(hashTable, i.usr, i);
          printMap(hashTable);
      
        }

         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("1st Order");
     printf("OrderId taker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
   printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);
   
    send_trade(c.exe->x[i]);
    // unxs_clr(c.exe);
}

clob_prnt(c);

}

Now Sir I am passing this function value through  hardcode like below and its working fine, am getting all clob_oid_t .

        clob_t c;
c = make_clob();
 c.exe = make_unxs(MODE_BI);

 struct hashMap *hashTable;
int tableSize = 1;
 hashTable = createMap(tableSize);

orderplace(c,1,100,"1",struct hashMap *hashTable) //Here 1 isthe orderid
orderplace(c,1,100,"2",struct hashMap *hashTable) //Here 2 is the orderid

But instead of hardcode if I pass the value through dynamic like below and if pass it through loop/ more that one time then old clob_oid_t is getting replaced by new clob_oid_t value.  I do not know what is the issue if pass it through hardcode more than one time all time I am getting different different clob_oi_t value. But in dynamic it is the issue. 

   printf("Enter Amount\n");
          scanf("%lf",&amt);
         printf("Enter Price\n");
         scanf("%lf",&price);
          printf("Enter offerid\n");
        scanf("%s",&output);
       orderplace(c,amt,price,output,hashTable);

Sir please please guide me.

**Comment by hroptatyr** [comment]
You're storing the same pointer (`output`) over and over again.  You need to generate a new pointer (e.g. by using `strdup()`) for every order.

**Comment by shanhashcah** [comment]
Thank U so much Sir
