### ISSUE TITLE
Obtain the order book

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#5]
Hi @hroptatyr 

Here  I am placing my order and showing the orderbook.

clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_ASK, 1, 0.0dd, .lmt =100, .usr = (uintptr_t) "1"},NANPX);
          

       if (o.qty.dis + o.qty.hid > 0.dd) {
        /* put remainder of order into book */
        clob_oid_t i = clob_add(c, o);
      printf("orderid..%s\n", i.usr);
        
  }

clob_prnt(c); // For showing the orderbook.

clob_prnt(c)  showing the orderbook as printed value. But Sir I need to keep it in some variable or something like this, so that I can able to customize it.

Thank U

**Comment by hroptatyr** [comment]
`clob_prnt` is for debugging.  The whole book can be iterated via iterators, and there are two of them, aggregated or disaggregated.  For aggregates:

    clob_aggiter_t i = clob_aggiter(c, CLOB_TYPE_LMT, CLOB_SIDE_BID);
    while (clob_aggiter_next(&i)) {
                printf("%f %f\n", (double)i.p, (double)(i.q.dis + i.q.hid));
    }

Similarly for `CLOB_SIDE_ASK`. And if you need to see market orders as well use `CLOB_TYPE_MKT` as second argument.  Essentially, look at `test/clob_06.c` or, for disaggregated iterators `test/clob_07.c`.

**Comment by hroptatyr** [comment]
Also note, in the example above I printed the hidden sizes.  If you're planning on passing the book to your users you'd probably keep those secret.

**Comment by shanhashcah** [comment]
Okay Sir.. Thanks

Let me try

Now Sir I want to expose RET API for orderbook which will return JSON data and also I want to create API for order place ,cancel etc.  So Sir how would I create API for C. Please give me some suggestion/hint. Because after all I need to expose API to UI otherwise I can not build a real project. Please help.

**Comment by hroptatyr** [comment]
I wouldn't create an API for or in C, use Ruby, Nodejs or Python for that. And to connect to your exchange system you can use an ordinary socket (TCP or unix-domain) and a custom, ad-hoc protocol.

**Comment by shanhashcah** [comment]
Okay Sir.. Let me do that.

Thank You
