### ISSUE TITLE
Storing orders into Database

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#6]
Hi @hroptatyr 

Actually we are compiling my source file which is stored in clob/src folder as below

cc -o  orderbook  -I../src ./orderbook.c ../src/libclob.a

Now Sir we want keep orders into database i.e  postgreSQL  and for postgreSQL  we have to include  <libpq-fe.h> library.
 For compiling we have to pass   -I/usr/include/postgresql -lpq  line at compile time. 

So Sir please help how can I add  -I/usr/include/postgresql -lpq command with  cc -o  orderbook  -I../src ./orderbook.c ../src/libclob.a 

Thanks

**Comment by hroptatyr** [comment]
Just like you suggested:

    cc -o orderbook -I/usr/include/postgresql -I../src ./orderbook.c -L/usr/lib -lpq ../src/libclob.a

or instead of `/usr/lib` the path where libpq.so can be found.

**Comment by shanhashcah** [comment]
Okay Sir..Let me try... Thanks...
