### ISSUE TITLE
Multiple Symbol in clob

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#7]
Hi @hroptatyr 

For placing order we need clob_t and we need to create a variable of clob_t  type as below
clob_t c;
c = make_clob();
 c.exe = make_unxs(MODE_BI);
Now Sir if I want to create multiple symbol  so I need to create multiple variable like clob_t c,c1,c2,c3.c4 and I need to pass respective variable to unxs_order function like clob_ord_t o1 = unxs_order(c, (clob_ord_t){i1.typ, i1.sid, amt , 0.0dd,.lmt =price, .usr = i1.usr},NANPX);

But Sir I need to keep backup all offers into db because in production suppose my clob program suddenly get stopped. Then I can easily push all offers from db to unxs_order function one by one. But here I need to identify clob_t for every single order. In db it is not possible to store clob_t  type. 

Please Sir give me some hint/suggestion to overcome this big issue.

**Comment by hroptatyr** [comment]
Sotre the symbol in the database and use a look-up table (e.g. a hash table) that maps symbols to `clob_t` objects.

**Comment by shanhashcah** [comment]
Ok..Let me do it.

Thanks
