### ISSUE TITLE
Unable to Store Order from clob to DB

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#8]
Hi @hroptatyr 

I am using postgresql and want to keep data from clob to DB. Below is my code.

If I am using sprintf() function to write the INSERT query inside my below code, getting Segmentation fault (core dumped) error.

PGconn *conn = PQconnectdb("dbname=maching_c host=localhost user=test password=test");

    if (PQstatus(conn) == CONNECTION_BAD) {
        
        fprintf(stderr, "Connection to database failed: %s\n",
            PQerrorMessage(conn));
        do_exit(conn);
    }

char query[1000];
 fscanf(fptr,"%d", &offerid);
        char output[19];

        sprintf(output, "%d",offerid);
       fclose(fptr);

          printf("Enter Amount\n");
          scanf("%lf",&amt);
          printf("Enter Price\n");
         scanf("%lf",&price);
         char *out=strdup(output);
         printf("Enter Side..");
        scanf("%s",&side);
         if (!strcmp(side, "ASK")) {
    parsed_side = CLOB_SIDE_ASK;
   } else if (!strcmp(side, "BID")) {
    parsed_side = CLOB_SIDE_BID;
    } 
       //orderplace(c,parsed_side,amt,price,out,hashTable,side);
clob_ord_t o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, parsed_side, amt, 0.0dd, .lmt =price, .usr = (uintptr_t) out},NANPX);
if (o.qty.dis + o.qty.hid > 0.dd) {
        /* put remainder of order into book */
        clob_oid_t i = clob_add(c, o);
       //printf("orderid..%lu\n", i.usr);
         printf("orderid..%s\n", i.usr);
         insertMap(hashTable, i.usr, i);
          printMap(hashTable);
        
         sprintf(query,"INSERT INTO offers(offerid,symbol,amount,price,action) VALUES('%s','%s',%lf,%lf,'%s');",i.usr,'1',amt,price,side);  ------> This line terminate the program

       
       PGresult *res=PQexec(conn,query);
     printf("Record Inserted");
          PQclear(res);  
         PQfinish(conn); 
        
               
    
}

But insted sprintf() function if  am using below code, it will work but here I am unable to pass variable which I will get data from clob.
PGresult *res=PQexec(conn, "INSERT INTO offers(offerid,symbol,amount,price,action) VALUES('1','1',12,100,'ASK')");
 

But Sir non-clob project can able to run INSERT query using sprintf() function  which I shared you in my code.

Please Sir any suggestion.

**Comment by hroptatyr** [comment]
But `sprintf()` is a routine from libc.  Read its documentation here: https://linux.die.net/man/3/sprintf

**Comment by shanhashcah** [comment]
Sir @hroptatyr 
Insert query using sprintf() function well in my below program

#include <stdio.h>
#include <stdlib.h>
#include <libpq-fe.h>

void do_exit(PGconn *conn, PGresult *res) {
    
    fprintf(stderr, "%s\n", PQerrorMessage(conn));    

    PQclear(res);
    PQfinish(conn);    
    
    exit(1);
}
int main() {
    
    PGconn *conn = PQconnectdb("dbname=maching_c host=54.219.253.192 user=paybito_match password=p@BI20@Dmin43");

    if (PQstatus(conn) == CONNECTION_BAD) {
        
        fprintf(stderr, "Connection to database failed: %s\n",
            PQerrorMessage(conn));
        //do_exit(conn);
    }
    
    char *user = PQuser(conn);
    char *db_name = PQdb(conn);
    char *pswd = PQpass(conn);
    
    printf("User: %s\n", user);
    printf("Database name: %s\n", db_name);
    printf("Password: %s\n", pswd);
    char x[5];
    char symbol[5];
    char side[5];
    double amt;
    double price;
    printf("Enter Offerid");
    scanf("%s",&x);
    printf("Enter Symbol");
    scanf("%s",&symbol);
    printf("Enter Side");
     scanf("%s",&side);
    
    printf("Enter Amount");
    scanf("%lf",&amt);
    printf("Enter Price");
    scanf("%lf",&price);
    char buffer[100];
    sprintf(buffer,"INSERT INTO offers(offerid,symbol,amount,price,action) VALUES('%s','%s',%lf,%lf,'%s');",x,symbol,amt,price,side);
    PGresult *res=PQexec(conn, buffer);
      if (PQresultStatus(res) != PGRES_COMMAND_OK) {
        do_exit(conn, res);   
       printf("Record Not");
    }
    
    PQclear(res);  
    PQfinish(conn);
    return 0;
}

So Sir I do not understand whats wrong I have done in my orderbook program.

**Comment by hroptatyr** [comment]
Yes I see, but that's a problem with `sprintf`.

**Comment by shanhashcah** [comment]
So Sir when I use sprintf() function for writing query in other project it works, but in clob it is not working. If ido not use sprintf() function then how would I insert data from clob to db via passing variable. Thats the issue.

**Comment by shanhashcah** [comment]
My main objective is taking data from clob through variable and passing those varible in insert query. That is why I was using sprintf().  So Sir please help.

**Comment by hroptatyr** [comment]
I don't know how to access a database.  Is `sprintf` the only option?  And if so, the issue should be raised with libc.  Again `sprintf` is not part of clob or in clob.

**Comment by shanhashcah** [comment]
Actually Sir sprinf() function for inserting data working well in other project but not in clob project. This is the issue. If you ask I can share  you both code.

**Comment by shanhashcah** [comment]
Ok Sir..Let me try with other function and if I will get any difficulty I will share with in my next post.
