### ISSUE TITLE
Db connection in Clob project

### ISSUE THREAD

**Issue by shanhashcah** [hroptatyr/clob#9]
Hi @hroptatyr 

Here I am trying to storing data in postgesql via PQexecPrepared command in my clob project , here it is showing no error but data not getting stored in DB. Below is my code.

clob_t c;
	c = make_clob();
        c.exe = make_unxs(MODE_BI);
        clob_ord_t o;

PGconn *conn = PQconnectdb("dbname=maching_c host=localhost user=paybito_match password=p@BI20@Dmin43");

    if (PQstatus(conn) == CONNECTION_BAD) {
        
        fprintf(stderr, "Connection to database failed: %s\n",
            PQerrorMessage(conn));
        
    }
const char command[]="INSERT INTO offers VALUES($1,$2,$3);";
int nParams=3;
char symbol[2]="1";
char output[19]="1";
char side[3]="ASK";

const char *const paramValues[] ={output,symbol,side};
const int paramLengths[] = {sizeof(output),sizeof(symbol),sizeof(side)};
const int paramFormats[] = {0, 0};
  int resultFormat = 0;
PGresult *res=PQexecPrepared(conn, command, nParams, paramValues, paramLengths,
                     paramFormats, resultFormat);

PQclear(res);

o=unxs_order(c, (clob_ord_t){CLOB_TYPE_LMT, CLOB_SIDE_BID, 2.0dd, 0.0dd, .lmt = 4500.00dd, .usr = (uintptr_t) output},NANPX);
      clob_oid_t  i;
if (o.qty.dis + o.qty.hid > 0.dd) {
    /* put remainder of order into book */
   i = clob_add(c, o);
   //printf("orderid..%lu\n", i.usr);
  printf("orderid..%s\n", i.usr);

}   
        

         /* print trades */
for (size_t i = 0U; i < c.exe->n; i++) {
     printf("2nd Order");
     printf("OrderId taker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].usr);
    printf("OrderId maker..%lu\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].usr);
     printf("Taker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_TAKER].sid);
   printf("Maker Side...%hhd\n",c.exe->o[MODE_BI*i+CLOB_SIDE_MAKER].sid);

   qty_t t1=c.exe->q[MODE_BI*i+CLOB_SIDE_TAKER];
  qty_t m1=c.exe->q[MODE_BI*i+CLOB_SIDE_MAKER];
   printf("Taker Remaning Qty..%f\n",(double)t1.dis);
  printf("Maker Remaning Qty...%f\n",(double)m1.dis);
    send_trade(c.exe->x[i]);
   
   
}

printf("Before order delation\n");

clob_prnt(c);

**Comment by hroptatyr** [comment]
This could be anything. And I cannot test it because it assumes a postgres setup.

**Comment by shanhashcah** [comment]
Okay @hroptatyr ..
